// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb4XsW6LCQSLGNyL-cNAm6ylzMdZZvzHQ',
    appId: '1:441773543598:web:3b8245a47346e48bb05d3f',
    messagingSenderId: '441773543598',
    projectId: 'mynotes-flutter-project-timo',
    authDomain: 'mynotes-flutter-project-timo.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-timo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5M4EiJeEfXVLFYac7uA2WlTwvP-fTa4w',
    appId: '1:441773543598:android:766566db1a330e18b05d3f',
    messagingSenderId: '441773543598',
    projectId: 'mynotes-flutter-project-timo',
    storageBucket: 'mynotes-flutter-project-timo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUg9KV7QPhzLpDZ1toUINtw7wlyc1X93s',
    appId: '1:441773543598:ios:2094a4555d628eb8b05d3f',
    messagingSenderId: '441773543598',
    projectId: 'mynotes-flutter-project-timo',
    storageBucket: 'mynotes-flutter-project-timo.appspot.com',
    iosClientId: '441773543598-6haenug8b5k2nkv37drrkipr2817ab7c.apps.googleusercontent.com',
    iosBundleId: 'com.timotiustech.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUg9KV7QPhzLpDZ1toUINtw7wlyc1X93s',
    appId: '1:441773543598:ios:2094a4555d628eb8b05d3f',
    messagingSenderId: '441773543598',
    projectId: 'mynotes-flutter-project-timo',
    storageBucket: 'mynotes-flutter-project-timo.appspot.com',
    iosClientId: '441773543598-6haenug8b5k2nkv37drrkipr2817ab7c.apps.googleusercontent.com',
    iosBundleId: 'com.timotiustech.mynotes',
  );
}
